name = "NowcastLSTM"
uuid = "b0f5751a-485a-11ec-1664-11f27ef34d7c"
author = ["Daniel Hopp <daniel.hopp1@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
CSV = "≥ 0.6.1"
DataFrames = "≥ 0.20.0"
julia = "≥ 1.0.0"
PyCall = "≥ 1.92.5"
